"""Build a clean folder for the Google Drive submission.

The brief asks for "all project-related files" on Drive with public view access.
Copying the working directory as-is would publish `.env` — a live MongoDB
connection string — to a link anyone can open. This script copies what should be
shared and refuses to copy what should not.

Usage:
    python scripts/package_submission.py
    python scripts/package_submission.py --out "D:/submission" --zip
"""

from __future__ import annotations

import argparse
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

#: Copied into the submission.
INCLUDE = [
    "src", "api", "tests", "scripts", "notebooks", "docs", "deploy",
    "dashboard/src", "dashboard/public",
    "README.md", "requirements.txt", "requirements-serve.txt",
    "pyproject.toml", "Dockerfile", "docker-compose.yml", "render.yaml",
    "docker-entrypoint.sh", ".env.example", ".gitignore", ".gitattributes",
    ".dockerignore", ".github",
    "dashboard/package.json", "dashboard/package-lock.json",
    "dashboard/vite.config.js", "dashboard/index.html",
    "dashboard/nginx.conf", "dashboard/Dockerfile", "dashboard/vercel.json",
    "dashboard/.env.example", "dashboard/.gitignore",
    "reports/FINAL_REPORT.md", "reports/metrics.json",
    "reports/logs",
]

#: Never copied, whatever else matches. Credentials, caches, build output and
#: multi-hundred-megabyte artefacts that a reviewer does not need.
EXCLUDE_NAMES = {
    ".env", ".env.local", ".env.production",
    "node_modules", "__pycache__", ".pytest_cache", ".ruff_cache",
    ".vercel", ".git", "dist", ".ipynb_checkpoints", ".venv", "venv",
}
EXCLUDE_PATTERNS = ("*token*", "*secret*", "*.pem", "*.key", "*.joblib",
                    "*.safetensors", "*.onnx", "*.bin")


def _is_excluded(path: Path) -> bool:
    if any(part in EXCLUDE_NAMES for part in path.parts):
        return True
    return any(path.match(pattern) for pattern in EXCLUDE_PATTERNS)


def copy_item(relative: str, destination: Path) -> tuple[int, int]:
    source = ROOT / relative
    if not source.exists():
        return 0, 0

    copied = skipped = 0
    if source.is_file():
        if _is_excluded(source.relative_to(ROOT)):
            return 0, 1
        target = destination / relative
        target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(source, target)
        return 1, 0

    for path in source.rglob("*"):
        if not path.is_file():
            continue
        relative_path = path.relative_to(ROOT)
        if _is_excluded(relative_path):
            skipped += 1
            continue
        target = destination / relative_path
        target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(path, target)
        copied += 1
    return copied, skipped


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", default=str(ROOT.parent / "PulseAI-Submission"))
    parser.add_argument("--zip", action="store_true", help="also produce a .zip")
    args = parser.parse_args()

    destination = Path(args.out)
    if destination.exists():
        shutil.rmtree(destination)
    destination.mkdir(parents=True)

    total_copied = total_skipped = 0
    for item in INCLUDE:
        copied, skipped = copy_item(item, destination)
        total_copied += copied
        total_skipped += skipped

    # A reviewer opening the folder should know immediately how to run it and
    # where the live versions are.
    (destination / "START_HERE.txt").write_text(
        "PulseAI - Customer Sentiment Intelligence Platform\n"
        "AI Major Capstone Project\n"
        "\n"
        "LIVE\n"
        "  Dashboard  https://pulseai-dashboard.vercel.app\n"
        "  API docs   https://pulseai-api-vb9h.onrender.com/docs\n"
        "  Source     https://github.com/AkashKeshari111/pulseai-sentiment-dashboard\n"
        "  Model      https://huggingface.co/akashkeshari111/pulseai-distilbert-sentiment\n"
        "\n"
        "  The API sleeps after 15 minutes of inactivity on the free tier, so the\n"
        "  first request can take up to a minute.\n"
        "\n"
        "READ IN THIS ORDER\n"
        "  1. README.md                                  what it is, how to run it\n"
        "  2. notebooks/01_sentiment_analysis_capstone.ipynb   the full analysis\n"
        "  3. reports/FINAL_REPORT.md                    results and implications\n"
        "  4. docs/ARCHITECTURE.md                       system design\n"
        "\n"
        "NOT INCLUDED\n"
        "  Model weights (260 MB) and the dataset are regenerated by the training\n"
        "  scripts - see README.md. Environment files are excluded because they\n"
        "  hold database credentials.\n",
        encoding="utf-8",
    )

    # Fail loudly rather than shipping a credential.
    leaked = [
        p for p in destination.rglob("*")
        if p.is_file() and (p.name == ".env" or "token" in p.name.lower())
    ]
    print(f"\n  copied {total_copied} files, skipped {total_skipped}")
    print(f"  output: {destination}")

    if leaked:
        print("\n  REFUSING TO CONTINUE - credential-like files were copied:")
        for path in leaked:
            print("   ", path.relative_to(destination))
        return 1
    print("  credential check: clean")

    if args.zip:
        archive = shutil.make_archive(str(destination), "zip", destination)
        size_mb = Path(archive).stat().st_size / 1024 / 1024
        print(f"  archive: {archive}  ({size_mb:.1f} MB)")

    print("\n  Upload this folder to Google Drive and set sharing to")
    print("  \"Anyone with the link can view\".\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
